theme: minima
title: Tech Reflections.
description: A collection of posts on the technical stuff I'm currently working with.
author: Axel Vanraes
future: false
show_drafts: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
