theme: minima
title: Tech Reflections.
description: Writing about my experiences with technology.
author: Axel Vanraes
future: false
markdown: GFM
show_drafts: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
